ingress:
    certificateArn: ENC[AES256_GCM,data:kvwcpjh5WadciBjsXyYPlgljomZIqNfZ7MnBGSlo0t1MhidW1lJyt6ol4RP76cnxq7cRjSQ0wjmvZC8DZd9waF+W3/DcEuRB8CBpM3IehTngvEXO6vLcgQ==,iv:sdMZ2G2nrUhAut8Ez3F/XSVgc/n1oFozfdz+p5q13AE=,tag:gfC9A8+j4Eo7JSZlDodBug==,type:str]
#ENC[AES256_GCM,data:nBft5PVT6VNM18fi1Ss3QpfVMkEIrLjfXw69Asj816epGskJh91qwUI5KhH4ulSpBfVvCE5uTG3n86K7Hm3gJxT2Zy9Jt8Z9xOBKTVr5dut7uYbrOTLDUMaiEBBx97p0YqFHuw==,iv:g9GQtujxrWV37zwNeplmuMvCsSl6Q5PvcwEIZzeV0SA=,tag:dE6xd3JxjwJ+K8KwAyg2HA==,type:comment]
spring:
    dbPassword: ENC[AES256_GCM,data:CBNspA==,iv:6g8eluK2FFj6rOAWUZUkohOCdoNiZjzz3FCaDq0vJAk=,tag:QjDQgWrtKbHh3VtDbqEy1g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:533267446521:key/bd93379d-e7de-4ceb-a587-d1052cd3d5e4
          created_at: "2026-02-11T04:26:12Z"
          enc: AQICAHgo4m5BGVHKFwu9PxuSTFaxHaojGk8ozQU5bkEwSJhZeAGC7h8hU+5Vn3WvvNWmyTLsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSvwSaQEGgqu12Rz9AgEQgDuQfrZAnsBOUQxTlHr6elrE0rCfPFhrCB6x4V28v3ryuFHCueQAcOkVS2i+k0cN7GEK69Q/jyTdmydJ5g==
          aws_profile: ""
    lastmodified: "2026-02-11T04:26:12Z"
    mac: ENC[AES256_GCM,data:agBwnktJGCz423PD049A9ruFMCYwQypkFfmLMSKKgN1RPzUN9JGOxmPoDmc72C+CUdY/qv1p/hXLKtoYDZssSeFmyjG7VMfSSxoQxnvB20y8mWna+qWKyZhAl1lPoUGITeH8erCJ+bGzTN348kfxXZYyxiS8859mnZObjMMy/5M=,iv:cpLQ4qdZvriXt1zgsJ3AVf+ZazIUn+udSXcVpnkna2A=,tag:MeX37XFmlJzRkcokePUgOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
