ingress:
    certificateArn: ENC[AES256_GCM,data:fXbea3agsqGSsRIS9u8+gF6BHzAcLB6Q1kHXVan3eyXsqBr5hHoNccxUFQKE6OauaFXuzQMFcNKvVxfmkAbt2hLoaQQ3uJFhGZCGEuA9BGo=,iv:R5cZkOyR5CPsHH2cMDBE1CpSx3n6zbx5QjfL2A8buxs=,tag:CHrUjHx+AdpmNjlAGS03fw==,type:str]
#ENC[AES256_GCM,data:sJ/VC+4E0tCmgmGpXisXr5BNcHL0DxyoM4M3I+z8/qL3/yFdyRq3xCtsAb3UkZi5sB+ZfPJWtXHrfNAVRxocQSoxdOLuShsPeetIWyr+qN7swfvIuJu+lUye/l2c+c7G3F+jYg==,iv:OnvhAAho87ZcpE2JnbQW7EXSUxmZpfQdo6l0lPiT7vc=,tag:oUWvuR9OkQFbOnsE/RiLNw==,type:comment]
spring:
    dbPassword: ENC[AES256_GCM,data:ye2wuQ==,iv:a7vT/P99Wa6CGAc7LcmLnz/qKaV8A7z+/GQGWH677bo=,tag:AM4ZcXtM5g6gvCAk2Ax0tw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:533267446521:key/bd93379d-e7de-4ceb-a587-d1052cd3d5e4
          created_at: "2026-02-11T03:59:04Z"
          enc: AQICAHgo4m5BGVHKFwu9PxuSTFaxHaojGk8ozQU5bkEwSJhZeAGc1rfyAbTdwA03FuRiMTTmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpP7BnYapMT++YOApAgEQgDuylJ9KrHCH9UdeuvJuYpbZIwRm33ahvWUqJzzsIwxm8CIZYgE7aSbq/gJ5jCmAgpUVxFUBmCa982vnGw==
          aws_profile: ""
    lastmodified: "2026-02-11T03:59:04Z"
    mac: ENC[AES256_GCM,data:X/5URPWx5nHcdoziTlubV1bk8BFxiEAsGS4I/ZzRANGjdUFR9MrSxkTqHBrWls27dgSCmoGH00CGHNCPRuUKsN6FV69N4KjuNW13Q0R/ALqofi9WzAUSqJ5DCnW2DJuDy4Oclk0JWbCcrpAL8c2aWD82Kg1kAgCm4g8oCNq7d2Y=,iv:/CV+NfX/wm1fxXLRBt+mPC5iPPCd5v/W5RLGluMDReQ=,tag:YgH/bKArtCwq7VEUEv5cOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
